---
- hosts: "{{setupHosts}}"
  gather_facts: no
  vars_prompt:
    - name: "setupHosts"
      prompt: "What host do you want to execute against?"
      private: no
  vars_files:
    - users.yml
  tasks:
    - name: "Create {{ item.name }} user"
      user:
        name: "{{ item.name }}"
        groups: wheel
        append: yes
      with_items: "{{ users }}"
    - name: "Create {{ item.name }} user .ssh folder"
      file:
        path: "/home/{{ item.name }}/.ssh/"
        state: directory
        mode: '0700'
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      with_items: "{{ users }}"
    - name: "Create {{ item.name }} user authorized_keys"
      file:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        state: touch
      with_items: "{{ users }}"
    - name: "Insert public key into {{ item.name }} user authorized_keys"
      lineinfile:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        state: present
        line: "{{ item.pubkey }}"
        create: yes
      with_items: "{{ users }}"
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#    - name: Disable root login
#      lineinfile:
#        path: /etc/ssh/sshd_config
#        regexp: '^PermitRootLogin'
#        line: 'PermitRootLogin no'
