---
- hosts: mta_prod
  gather_facts: false

  tasks:
    - name: uptime
      shell: "uptime"
      register: uptime

    - name: nginx_status
      uri:
        url: "http://localhost/nginx_status"
        return_content: yes
        method: GET
      register: nginxstatus
